# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.srcs/sources_1/ip/fifo_ddr4_buf/fifo_ddr4_buf.xci
# IP: The module: 'fifo_ddr4_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/fifo_ddr4_buf/fifo_ddr4_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr4_buf'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/fifo_ddr4_buf/fifo_ddr4_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr4_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.srcs/sources_1/ip/fifo_ddr4_buf/fifo_ddr4_buf.xci
# IP: The module: 'fifo_ddr4_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/fifo_ddr4_buf/fifo_ddr4_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr4_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/fifo_ddr4_buf/fifo_ddr4_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr4_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
