set_property SRC_FILE_INFO {cfile:/home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.srcs/constrs_1/new/constrains.xdc rfile:../../../zcu102_pl_ddr4.srcs/constrs_1/new/constrains.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list ddr4_u/inst/u_ddr4_infrastructure/u_bufg_divClk_0]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 25 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {mig_fifo_u/ddr4_wr_addr[0]} {mig_fifo_u/ddr4_wr_addr[1]} {mig_fifo_u/ddr4_wr_addr[2]} {mig_fifo_u/ddr4_wr_addr[3]} {mig_fifo_u/ddr4_wr_addr[4]} {mig_fifo_u/ddr4_wr_addr[5]} {mig_fifo_u/ddr4_wr_addr[6]} {mig_fifo_u/ddr4_wr_addr[7]} {mig_fifo_u/ddr4_wr_addr[8]} {mig_fifo_u/ddr4_wr_addr[9]} {mig_fifo_u/ddr4_wr_addr[10]} {mig_fifo_u/ddr4_wr_addr[11]} {mig_fifo_u/ddr4_wr_addr[12]} {mig_fifo_u/ddr4_wr_addr[13]} {mig_fifo_u/ddr4_wr_addr[14]} {mig_fifo_u/ddr4_wr_addr[15]} {mig_fifo_u/ddr4_wr_addr[16]} {mig_fifo_u/ddr4_wr_addr[17]} {mig_fifo_u/ddr4_wr_addr[18]} {mig_fifo_u/ddr4_wr_addr[19]} {mig_fifo_u/ddr4_wr_addr[20]} {mig_fifo_u/ddr4_wr_addr[21]} {mig_fifo_u/ddr4_wr_addr[22]} {mig_fifo_u/ddr4_wr_addr[23]} {mig_fifo_u/ddr4_wr_addr[24]}]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 25 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {mig_fifo_u/ddr4_2wr[0]} {mig_fifo_u/ddr4_2wr[1]} {mig_fifo_u/ddr4_2wr[2]} {mig_fifo_u/ddr4_2wr[3]} {mig_fifo_u/ddr4_2wr[4]} {mig_fifo_u/ddr4_2wr[5]} {mig_fifo_u/ddr4_2wr[6]} {mig_fifo_u/ddr4_2wr[7]} {mig_fifo_u/ddr4_2wr[8]} {mig_fifo_u/ddr4_2wr[9]} {mig_fifo_u/ddr4_2wr[10]} {mig_fifo_u/ddr4_2wr[11]} {mig_fifo_u/ddr4_2wr[12]} {mig_fifo_u/ddr4_2wr[13]} {mig_fifo_u/ddr4_2wr[14]} {mig_fifo_u/ddr4_2wr[15]} {mig_fifo_u/ddr4_2wr[16]} {mig_fifo_u/ddr4_2wr[17]} {mig_fifo_u/ddr4_2wr[18]} {mig_fifo_u/ddr4_2wr[19]} {mig_fifo_u/ddr4_2wr[20]} {mig_fifo_u/ddr4_2wr[21]} {mig_fifo_u/ddr4_2wr[22]} {mig_fifo_u/ddr4_2wr[23]} {mig_fifo_u/ddr4_2wr[24]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 25 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {mig_fifo_u/ddr4_rd_addr[0]} {mig_fifo_u/ddr4_rd_addr[1]} {mig_fifo_u/ddr4_rd_addr[2]} {mig_fifo_u/ddr4_rd_addr[3]} {mig_fifo_u/ddr4_rd_addr[4]} {mig_fifo_u/ddr4_rd_addr[5]} {mig_fifo_u/ddr4_rd_addr[6]} {mig_fifo_u/ddr4_rd_addr[7]} {mig_fifo_u/ddr4_rd_addr[8]} {mig_fifo_u/ddr4_rd_addr[9]} {mig_fifo_u/ddr4_rd_addr[10]} {mig_fifo_u/ddr4_rd_addr[11]} {mig_fifo_u/ddr4_rd_addr[12]} {mig_fifo_u/ddr4_rd_addr[13]} {mig_fifo_u/ddr4_rd_addr[14]} {mig_fifo_u/ddr4_rd_addr[15]} {mig_fifo_u/ddr4_rd_addr[16]} {mig_fifo_u/ddr4_rd_addr[17]} {mig_fifo_u/ddr4_rd_addr[18]} {mig_fifo_u/ddr4_rd_addr[19]} {mig_fifo_u/ddr4_rd_addr[20]} {mig_fifo_u/ddr4_rd_addr[21]} {mig_fifo_u/ddr4_rd_addr[22]} {mig_fifo_u/ddr4_rd_addr[23]} {mig_fifo_u/ddr4_rd_addr[24]}]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 25 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {mig_fifo_u/ddr4_2rd[0]} {mig_fifo_u/ddr4_2rd[1]} {mig_fifo_u/ddr4_2rd[2]} {mig_fifo_u/ddr4_2rd[3]} {mig_fifo_u/ddr4_2rd[4]} {mig_fifo_u/ddr4_2rd[5]} {mig_fifo_u/ddr4_2rd[6]} {mig_fifo_u/ddr4_2rd[7]} {mig_fifo_u/ddr4_2rd[8]} {mig_fifo_u/ddr4_2rd[9]} {mig_fifo_u/ddr4_2rd[10]} {mig_fifo_u/ddr4_2rd[11]} {mig_fifo_u/ddr4_2rd[12]} {mig_fifo_u/ddr4_2rd[13]} {mig_fifo_u/ddr4_2rd[14]} {mig_fifo_u/ddr4_2rd[15]} {mig_fifo_u/ddr4_2rd[16]} {mig_fifo_u/ddr4_2rd[17]} {mig_fifo_u/ddr4_2rd[18]} {mig_fifo_u/ddr4_2rd[19]} {mig_fifo_u/ddr4_2rd[20]} {mig_fifo_u/ddr4_2rd[21]} {mig_fifo_u/ddr4_2rd[22]} {mig_fifo_u/ddr4_2rd[23]} {mig_fifo_u/ddr4_2rd[24]}]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {mig_fifo_u/cnt_data[0]} {mig_fifo_u/cnt_data[1]} {mig_fifo_u/cnt_data[2]} {mig_fifo_u/cnt_data[3]} {mig_fifo_u/cnt_data[4]} {mig_fifo_u/cnt_data[5]} {mig_fifo_u/cnt_data[6]} {mig_fifo_u/cnt_data[7]} {mig_fifo_u/cnt_data[8]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {mig_fifo_u/cnt_cmd[0]} {mig_fifo_u/cnt_cmd[1]} {mig_fifo_u/cnt_cmd[2]} {mig_fifo_u/cnt_cmd[3]} {mig_fifo_u/cnt_cmd[4]} {mig_fifo_u/cnt_cmd[5]} {mig_fifo_u/cnt_cmd[6]} {mig_fifo_u/cnt_cmd[7]} {mig_fifo_u/cnt_cmd[8]}]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {test_u/cnt_err[0]} {test_u/cnt_err[1]} {test_u/cnt_err[2]} {test_u/cnt_err[3]} {test_u/cnt_err[4]} {test_u/cnt_err[5]} {test_u/cnt_err[6]} {test_u/cnt_err[7]} {test_u/cnt_err[8]} {test_u/cnt_err[9]} {test_u/cnt_err[10]} {test_u/cnt_err[11]} {test_u/cnt_err[12]} {test_u/cnt_err[13]} {test_u/cnt_err[14]} {test_u/cnt_err[15]} {test_u/cnt_err[16]} {test_u/cnt_err[17]} {test_u/cnt_err[18]} {test_u/cnt_err[19]} {test_u/cnt_err[20]} {test_u/cnt_err[21]} {test_u/cnt_err[22]} {test_u/cnt_err[23]} {test_u/cnt_err[24]} {test_u/cnt_err[25]} {test_u/cnt_err[26]} {test_u/cnt_err[27]} {test_u/cnt_err[28]} {test_u/cnt_err[29]} {test_u/cnt_err[30]} {test_u/cnt_err[31]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
