# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.srcs/sources_1/ip/ddr4_core/ddr4_core.xci
# IP: The module: 'ddr4_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_1/ddr4_core_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_core_phy || ORIG_REF_NAME==ddr4_core_phy} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_0/ddr4_core_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_core_microblaze_mcs || ORIG_REF_NAME==ddr4_core_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/bd_bf3f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f || ORIG_REF_NAME==bd_bf3f} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_0/bd_bf3f_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_microblaze_I_0 || ORIG_REF_NAME==bd_bf3f_microblaze_I_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_1/bd_bf3f_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_rst_0_0 || ORIG_REF_NAME==bd_bf3f_rst_0_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_2/bd_bf3f_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_ilmb_0 || ORIG_REF_NAME==bd_bf3f_ilmb_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_3/bd_bf3f_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_dlmb_0 || ORIG_REF_NAME==bd_bf3f_dlmb_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_4/bd_bf3f_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_5/bd_bf3f_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_6/bd_bf3f_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_lmb_bram_I_0 || ORIG_REF_NAME==bd_bf3f_lmb_bram_I_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_7/bd_bf3f_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_8/bd_bf3f_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_9/bd_bf3f_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_bf3f_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_10/bd_bf3f_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_iomodule_0_0 || ORIG_REF_NAME==bd_bf3f_iomodule_0_0} -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_1/par/ddr4_core_phy_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_0/bd_bf3f_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_microblaze_I_0 || ORIG_REF_NAME==bd_bf3f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_0/bd_bf3f_microblaze_I_0_ooc_debug.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_1/bd_bf3f_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_rst_0_0 || ORIG_REF_NAME==bd_bf3f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_1/bd_bf3f_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_rst_0_0 || ORIG_REF_NAME==bd_bf3f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_2/bd_bf3f_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_ilmb_0 || ORIG_REF_NAME==bd_bf3f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_3/bd_bf3f_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_dlmb_0 || ORIG_REF_NAME==bd_bf3f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_6/bd_bf3f_lmb_bram_I_0_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_9/bd_bf3f_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_10/bd_bf3f_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_iomodule_0_0 || ORIG_REF_NAME==bd_bf3f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/bd_bf3f_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_0/ddr4_core_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_core_microblaze_mcs || ORIG_REF_NAME==ddr4_core_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_0/ddr4_core_microblaze_mcs_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ddr4_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_core'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/par/ddr4_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.srcs/sources_1/ip/ddr4_core/ddr4_core.xci
# IP: The module: 'ddr4_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_1/ddr4_core_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_core_phy || ORIG_REF_NAME==ddr4_core_phy} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_0/ddr4_core_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_core_microblaze_mcs || ORIG_REF_NAME==ddr4_core_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/bd_bf3f.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f || ORIG_REF_NAME==bd_bf3f} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_0/bd_bf3f_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_microblaze_I_0 || ORIG_REF_NAME==bd_bf3f_microblaze_I_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_1/bd_bf3f_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_rst_0_0 || ORIG_REF_NAME==bd_bf3f_rst_0_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_2/bd_bf3f_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_ilmb_0 || ORIG_REF_NAME==bd_bf3f_ilmb_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_3/bd_bf3f_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_dlmb_0 || ORIG_REF_NAME==bd_bf3f_dlmb_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_4/bd_bf3f_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_5/bd_bf3f_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_6/bd_bf3f_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_lmb_bram_I_0 || ORIG_REF_NAME==bd_bf3f_lmb_bram_I_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_7/bd_bf3f_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_8/bd_bf3f_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_bf3f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_9/bd_bf3f_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_bf3f_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_10/bd_bf3f_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bf3f_iomodule_0_0 || ORIG_REF_NAME==bd_bf3f_iomodule_0_0} -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_1/par/ddr4_core_phy_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_0/bd_bf3f_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_microblaze_I_0 || ORIG_REF_NAME==bd_bf3f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_0/bd_bf3f_microblaze_I_0_ooc_debug.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_1/bd_bf3f_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_rst_0_0 || ORIG_REF_NAME==bd_bf3f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_1/bd_bf3f_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_rst_0_0 || ORIG_REF_NAME==bd_bf3f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_2/bd_bf3f_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_ilmb_0 || ORIG_REF_NAME==bd_bf3f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_3/bd_bf3f_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_dlmb_0 || ORIG_REF_NAME==bd_bf3f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_6/bd_bf3f_lmb_bram_I_0_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_9/bd_bf3f_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/ip/ip_10/bd_bf3f_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bf3f_iomodule_0_0 || ORIG_REF_NAME==bd_bf3f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/bd_0/bd_bf3f_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_0/ddr4_core_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_core_microblaze_mcs || ORIG_REF_NAME==ddr4_core_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ip_0/ddr4_core_microblaze_mcs_ooc.xdc

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/ddr4_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/zchliu/work/Vivado_Project/zcu102_pl_ddr4/zcu102_pl_ddr4.gen/sources_1/ip/ddr4_core/par/ddr4_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
