
####################################################################################
####################################################################################


# Vivado Generated miscellaneous constraints 

set_property src_info {type:PI file:{} line:-1 export:NONE save:INPUT read:READ} [current_design]
set_property -quiet TOOL_DERIVED_CLK_NAMES 1:0:CLKIN:CLKOUTPHY:mmcm_clkout0:pll_clk [get_cells -quiet {inst/u_ddr4_phy_pll/plle_loop[0].gen_plle4.PLLE4_BASE_INST_OTHER}]

####################################################################################
# Constraints from file : 'ddr4_core.xdc'
####################################################################################

set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property ODT RTT_40 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE SDR [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property DATA_RATE DDR [get_ports {ddr4_dqs_t[1]}]

####################################################################################
# Constraints from file : 'ddr4_core_board.xdc'
####################################################################################

set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_act_n [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK8 [get_ports ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr0 [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM8 [get_ports {ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr1 [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM9 [get_ports {ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr2 [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP8 [get_ports {ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr3 [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8 [get_ports {ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr4 [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK10 [get_ports {ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr5 [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ10 [get_ports {ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr6 [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP9 [get_ports {ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr7 [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN9 [get_ports {ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr8 [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP10 [get_ports {ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr9 [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP11 [get_ports {ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr10 [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM10 [get_ports {ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr11 [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL10 [get_ports {ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr12 [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM11 [get_ports {ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr13 [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL11 [get_ports {ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr14 [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ7 [get_ports {ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr15 [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL5 [get_ports {ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_adr16 [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ9 [get_ports {ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_ba0 [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK12 [get_ports {ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_ba1 [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ12 [get_ports {ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_bg [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK7 [get_ports {ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_ck_c [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_ck_t [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP7 [get_ports {ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN7 [get_ports {ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_cke [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM3 [get_ports {ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_cs_n [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP2 [get_ports {ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dm_dbi_n0 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL6 [get_ports {ddr4_dm_dbi_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dm_dbi_n1 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN2 [get_ports {ddr4_dm_dbi_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq0 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK4 [get_ports {ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq1 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK5 [get_ports {ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq2 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN4 [get_ports {ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq3 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM4 [get_ports {ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq4 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP4 [get_ports {ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq5 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP5 [get_ports {ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq6 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM5 [get_ports {ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq7 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM6 [get_ports {ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq8 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK2 [get_ports {ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq9 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK3 [get_ports {ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq10 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL1 [get_ports {ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq11 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK1 [get_ports {ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq12 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN1 [get_ports {ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq13 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM1 [get_ports {ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq14 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP3 [get_ports {ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dq15 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN3 [get_ports {ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dqs_c0 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dqs_c1 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dqs_t0 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP6 [get_ports {ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN6 [get_ports {ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_dqs_t1 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL2 [get_ports {ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL3 [get_ports {ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_odt [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK9 [get_ports {ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN c0_ddr4_reset_n [get_ports ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH9 [get_ports ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN user_si570_sysclk_n [get_ports sys_clk_n]
set_property src_info {type:SCOPED_XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_n]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN user_si570_sysclk_p [get_ports sys_clk_p]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL7 [get_ports sys_clk_n]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL8 [get_ports sys_clk_p]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_p]
